# BASC Macrochan Scraper: Makefile
# 
# This is a Makefile that makes it easy to run all the 
# python scripts you need to scrape Macrochan, in order.
# 
# You can choose to just run `make` to start the whole process,
# or run `make database`, `make search-query`, or `make image-urls`

# amount of images currently on macrochan
IMGAMT=45175

all: database search-query image-urls

# step 0: create the database `macrochan-dump-*/macrochan.db`
database:
	python3 0-create-database.py

# step 1: start the search query
search-query:
	python3 1-search-query.py $(IMGAMT)

# step 2: obtain image URLs
image-urls:
	python3 2-list-image-urls.pyh

# delete all dump folders
clean:
	rm -rf macrochan-dump-*
